#!/bin/bash
# Cloudflare Pages - Git Integration Setup
# Run this once to connect your GitHub repo to Cloudflare Pages for auto-deployment

echo "🔗 Setting up Cloudflare Pages Git Integration..."
echo ""
echo "📋 Steps to complete in Cloudflare Dashboard:"
echo ""
echo "1. Go to: https://dash.cloudflare.com → Pages → goodflippindesign"
echo "2. Click 'Settings' → 'Builds & deployments'"
echo "3. Click 'Connect to Git' (if not already connected)"
echo "4. Select 'GitHub' and authorize"
echo "5. Choose repository: weave0/goodflippindesign"
echo "6. Configure build settings:"
echo "   - Production branch: main"
echo "   - Build command: npm run build"
echo "   - Build output directory: ."
echo "   - Root directory: /"
echo ""
echo "✅ Once connected, Cloudflare Pages will automatically:"
echo "   - Deploy on every push to main (FREE)"
echo "   - Create preview URLs for PRs (FREE)"
echo "   - Run: npm run build (cache-bust + sync)"
echo "   - No GitHub Actions minutes consumed!"
echo ""
echo "🌐 Your site will be live at:"
echo "   - https://goodflippindesign.pages.dev"
echo "   - https://goodflippindesign.com"
echo "   - https://www.goodflippindesign.com"
echo ""
echo "📊 Cost: $0/month (Cloudflare Pages free tier)"
echo "   - Unlimited deployments"
echo "   - Unlimited bandwidth"
echo "   - Automatic SSL"
echo "   - Git integration"
echo ""
echo "⚡ Alternative: Manual deployment via CLI:"
echo "   wrangler pages deploy . --project-name=goodflippindesign"
